README.md
Adding additional comments to the C# code to clarify code usage as it's currently unclear and it appears users should be using all six list items.
=> Update README.md comments

Excel.4.5/ExcelReaderFactory.cs
issue https://github.com/ExcelDataReader/ExcelDataReader/issues/83
=> Create reader based from the file signature issue #83

Excel/Core/OpenXmlFormat/XlsxWorkbook.cs
Fixes https://github.com/ExcelDataReader/ExcelDataReader/issues/108 and https://github.com/ExcelDataReader/ExcelDataReader/issues/12
Phonetic items represents pronunciation hints for some East Asian languages.
In the file 'xl/sharedStrings.xml', the phonetic properties appear like:
```
<si>
<t>(a japanese text in KANJI)</t>
<rPh sb="0" eb="1">
<t>(its pronounciation in KATAKANA)</t>
</rPh>
</si>
=> Handles multi-line text and ignores phonetic hint in shared strings (XLSX)

Excel/Log/LogManager.cs
Also made it slightly more efficient.
=> The LogManager should now be thread safe. This should fix #122 and #32.

Excel/Log/LogManager.cs, ExcelDataReader.Portable/Log/LogManager.cs
The LogManager should now be thread safe.
=> Made the same changes as in #123 to the portable code too.

Excel/Core/OpenXmlFormat/XlsxWorkbook.cs
Bugfix https://github.com/ExcelDataReader/ExcelDataReader/issues/12
=> Removed wrong ELSE IF, should be IF

Excel.Tests/FormatReaderTest.cs, ExcelDataReader.Portable/Core/FormatReader.cs
=> Take character width space specifiers into account

src/ExcelDataReader.DataSet/ExcelDataReader.DataSet.csproj, test/ExcelDataReader.Tests/ExcelDataReader.Tests.csproj, test/ExcelDataReader.Tests/MockDataSet/DataColumn.cs, test/ExcelDataReader.Tests/MockDataSet/DataColumnCollection.cs, test/ExcelDataReader.Tests/MockDataSet/DataRow.cs, test/ExcelDataReader.Tests/MockDataSet/DataRowCollection.cs, test/ExcelDataReader.Tests/MockDataSet/DataSet.cs, test/ExcelDataReader.Tests/MockDataSet/DataTable.cs, test/ExcelDataReader.Tests/MockDataSet/DataTableCollection.cs, test/ExcelDataReader.Tests/MockDataSet/PropertyCollection.cs
Don't want anyone accidentally using the mock DataSet implementation
=> Removed "netstandard1.3" support from DataSet project

README.md, src/ExcelDataReader.DataSet/ExcelDataReader.DataSet.csproj
These are the last touches before I plan doing a prerelease from the develop branch. When merged, can upload the latest packages from AppVeyor in a "Github Release" and tag the commit with the corresponding version. Can upload same packages to Nuget.org as well
=> Updated readme and dataset package description

src/ExcelDataReader/Core/BinaryFormat/XlsBiffStream.cs, src/ExcelDataReader/Core/BinaryFormat/XlsWorkbook.cs, src/ExcelDataReader/ExcelBinaryReader.cs, src/ExcelDataReader/ExcelDataReader.cs, src/ExcelDataReader/ExcelReaderConfiguration.cs, src/ExcelDataReader/ExcelReaderFactory.cs
=> Removed ReadOption.

src/ExcelDataReader/Core/BinaryFormat/XlsBiffFormulaCell.cs, src/ExcelDataReader/Core/BinaryFormat/XlsBiffSimpleValueRecord.cs, src/ExcelDataReader/Core/BinaryFormat/XlsByteString.cs, src/ExcelDataReader/Core/BinaryFormat/XlsDocument.cs, src/ExcelDataReader/Core/BinaryFormat/XlsHeader.cs, src/ExcelDataReader/Core/BinaryFormat/XlsWorksheet.cs, src/ExcelDataReader/Core/Helpers.cs, src/ExcelDataReader/Core/ReferenceHelper.cs, src/ExcelDataReader/ExcelBinaryReader.cs, src/ExcelDataReader/ExcelDataReader.cs, src/ExcelDataReader/ExcelOpenXmlReader.cs, src/ExcelDataReader/ExcelReaderFactory.cs
Removing unused things, a few xml doc fixes, inlined variables declarations, exlicit type instead of cast, enum instead of multiple property gets for formula cells..
=> Some minor changes

src/ExcelDataReader/Core/BinaryFormat/XlsSSTReader.cs, test/ExcelDataReader.Tests/Configuration.cs, test/ExcelDataReader.Tests/ExcelBinaryReaderTest.cs
=> Fixed reading single byte continuations.

src/ExcelDataReader/Core/CsvFormat/CsvParser.cs, test/ExcelDataReader.Tests/ExcelCsvReaderTest.cs
I changed ParseBuffer method definition and add boolean with information if it's end of buffer or not. If it is end of buffer and we still got something in RowResults, it means we need to parse any line feed character.
=> Git Issue 351 solution with test

src/ExcelDataReader/Core/CsvFormat/CsvAnalyzer.cs, src/ExcelDataReader/Core/CsvFormat/CsvWorkbook.cs, src/ExcelDataReader/Core/CsvFormat/CsvWorksheet.cs, src/ExcelDataReader/ExcelCsvReader.cs, src/ExcelDataReader/ExcelReaderConfiguration.cs, src/ExcelDataReader/ExcelReaderFactory.cs
I added the logic to allow the user to specify the number of rows to analyze within a csv. 
I also included a minor optimization
=> Is there an option to not analyze CSV file? #339

src/ExcelDataReader/Core/BinaryFormat/XlsWorkbook.cs
=> Ignore FORMAT records with a duplicate Index.

test/ExcelDataReader.Tests/MockDataSet/DataRow.cs, test/ExcelDataReader.Tests/MockDataSet/DataTable.cs
Improves test performance a little and makes it easier to find real hot spots while profiling.
=> Don't create a lot of unused arrays.

src/ExcelDataReader/Core/BinaryFormat/XlsWorkbook.cs, src/ExcelDataReader/Core/CommonWorkbook.cs, src/ExcelDataReader/Core/CsvFormat/CsvWorksheet.cs, src/ExcelDataReader/Core/ExtendedFormat.cs, src/ExcelDataReader/Core/OpenXmlFormat/BinaryFormat/BiffStylesReader.cs, src/ExcelDataReader/Core/OpenXmlFormat/XmlFormat/StringHelper.cs, src/ExcelDataReader/Core/OpenXmlFormat/XmlFormat/XmlStylesReader.cs, src/ExcelDataReader/Core/ReferenceHelper.cs, src/ExcelDataReader/ExcelDataReader.csproj, src/TestApp/Program.cs, src/TestApp/TestApp.csproj, test/ExcelDataReader.Tests/ExcelCsvReaderTest.cs, test/ExcelDataReader.Tests/ExcelDataReader.Tests.csproj, test/ExcelDataReader.Tests/ExcelTestBase.cs, test/ExcelDataReader.Tests/SetUpFixture.cs
Saw these while profiling a little for #525. Not a fix for that issue though since I don't know what's going on there.
=> Reduce allocations a little. 

src/ExcelDataReader/Core/OpenXmlFormat/XmlFormat/XmlWorksheetReader.cs
=> Fix for parsing worksheet column without "width" attribute.

src/ExcelDataReader/Core/OpenXmlFormat/ZipWorker.cs
fixed slow performance with big XLSB files and NET Core
https://github.com/ExcelDataReader/ExcelDataReader/issues/493
=> Hangs on XLSB file read

README.md
I think presenting the methods and their properties as a table improves readability.
=> List of methods and their properties as a table
